# Generated by Django 6.0.3 on 2026-03-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pj_code', models.CharField(max_length=12, unique=True, verbose_name='项目主数据编码')),
                ('pj_name', models.CharField(max_length=100, unique=True, verbose_name='项目名称')),
                ('org_name', models.CharField(max_length=50, verbose_name='项目机构名称')),
                ('org_code', models.CharField(max_length=9, verbose_name='项目机构组织编码')),
                ('parent_pj_code', models.CharField(max_length=12, verbose_name='上级PJ编码')),
                ('province_code', models.CharField(max_length=20, verbose_name='所在省')),
                ('city_code', models.CharField(max_length=20, verbose_name='所在市')),
                ('business_unit', models.CharField(max_length=50, verbose_name='业务板块')),
                ('dept', models.CharField(max_length=50, verbose_name='项目承担部门')),
                ('project_type', models.CharField(max_length=50, verbose_name='项目类型')),
                ('org_mode', models.CharField(max_length=50, verbose_name='项目组织模式')),
                ('data_status', models.CharField(max_length=50, verbose_name='主数据系统数据状态')),
                ('exec_pj_code', models.CharField(max_length=12, verbose_name='执行层PJ码')),
                ('year', models.CharField(max_length=4, verbose_name='项目年份')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.CharField(max_length=50, verbose_name='创建人')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=50, verbose_name='更新人')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
            ],
        ),
    ]
