# Generated by Django 5.1.14 on 2026-03-16 15:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='字典类型编码')),
                ('name', models.CharField(max_length=100, verbose_name='字典类型名称')),
                ('group', models.CharField(blank=True, max_length=50, verbose_name='字典分组')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='版本')),
                ('effective_start', models.DateField(blank=True, null=True, verbose_name='生效开始日期')),
                ('effective_end', models.DateField(blank=True, null=True, verbose_name='生效结束日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '字典类型',
                'verbose_name_plural': '字典类型',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, unique=True, verbose_name='导入批次号')),
                ('source_file', models.CharField(max_length=200, verbose_name='导入文件名')),
                ('imported_by', models.CharField(max_length=50, verbose_name='导入人')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='总行数')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='成功数')),
                ('fail_count', models.PositiveIntegerField(default=0, verbose_name='失败数')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
            ],
            options={
                'verbose_name': '导入批次',
                'verbose_name_plural': '导入批次',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=50, verbose_name='项目编码')),
                ('project_name', models.CharField(blank=True, max_length=200, verbose_name='项目名称')),
                ('approval_type', models.CharField(choices=[('update', '修改'), ('delete', '删除'), ('import', '导入')], max_length=10, verbose_name='审批类型')),
                ('before_data', models.JSONField(blank=True, null=True, verbose_name='修改前数据')),
                ('after_data', models.JSONField(blank=True, null=True, verbose_name='修改后数据')),
                ('change_note', models.CharField(blank=True, max_length=200, verbose_name='修改说明')),
                ('submitter', models.CharField(max_length=50, verbose_name='提交人')),
                ('approver', models.CharField(default='倪明珠', max_length=50, verbose_name='审批人')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='审批状态')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('approve_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approve_note', models.CharField(blank=True, max_length=200, verbose_name='审批意见')),
                ('import_file_path', models.CharField(blank=True, max_length=500, verbose_name='导入文件路径')),
            ],
            options={
                'verbose_name': '项目审批',
                'verbose_name_plural': '项目审批',
                'ordering': ['-submit_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^PJ\\d{10}$', '项目编号必须为PJ开头的12位编码')], verbose_name='项目主数据编码')),
                ('project_name', models.CharField(max_length=100, unique=True, verbose_name='项目名称')),
                ('org_name', models.CharField(max_length=50, verbose_name='项目机构名称')),
                ('parent_pj_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='上级PJ编码')),
                ('province_code', models.CharField(max_length=6, verbose_name='所在省')),
                ('city_code', models.CharField(max_length=6, verbose_name='所在市')),
                ('business_unit', models.CharField(max_length=50, verbose_name='业务板块')),
                ('dept', models.CharField(max_length=50, verbose_name='项目承担部门')),
                ('project_type', models.CharField(max_length=50, verbose_name='项目类型')),
                ('org_mode', models.CharField(max_length=50, verbose_name='项目组织模式')),
                ('data_status', models.CharField(max_length=50, verbose_name='主数据系统数据状态')),
                ('is_execution_level', models.BooleanField(default=False, verbose_name='是否为执行层')),
                ('project_year', models.CharField(max_length=4, verbose_name='项目年份')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.CharField(max_length=50, verbose_name='创建人')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=50, verbose_name='更新人')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('data_version', models.PositiveIntegerField(default=1, verbose_name='数据版本')),
            ],
            options={
                'verbose_name': '项目主数据',
                'verbose_name_plural': '项目主数据',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMasterLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=12, verbose_name='项目编码')),
                ('action', models.CharField(choices=[('create', '新增'), ('update', '变更'), ('delete', '删除'), ('import', '导入')], max_length=10, verbose_name='动作')),
                ('before_data', models.JSONField(blank=True, null=True, verbose_name='修改前')),
                ('after_data', models.JSONField(blank=True, null=True, verbose_name='修改后')),
                ('change_note', models.CharField(blank=True, max_length=200, verbose_name='修改说明')),
                ('operator', models.CharField(max_length=50, verbose_name='操作人')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '项目主数据日志',
                'verbose_name_plural': '项目主数据日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='行号')),
                ('field_name', models.CharField(blank=True, max_length=50, verbose_name='字段名')),
                ('error_message', models.CharField(max_length=500, verbose_name='错误原因')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='原始数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='documents.importbatch', verbose_name='导入批次')),
            ],
            options={
                'verbose_name': '导入错误',
                'verbose_name_plural': '导入错误',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户扩展信息',
                'verbose_name_plural': '用户扩展信息',
            },
        ),
        migrations.CreateModel(
            name='DictItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='字典项编码')),
                ('name', models.CharField(max_length=100, verbose_name='字典项名称')),
                ('value', models.CharField(blank=True, max_length=200, verbose_name='字典项值')),
                ('parent_code', models.CharField(blank=True, max_length=50, verbose_name='上级编码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='版本')),
                ('effective_start', models.DateField(blank=True, null=True, verbose_name='生效开始日期')),
                ('effective_end', models.DateField(blank=True, null=True, verbose_name='生效结束日期')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dict_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.dicttype', verbose_name='字典类型')),
            ],
            options={
                'verbose_name': '字典项',
                'verbose_name_plural': '字典项',
                'ordering': ['dict_type', 'sort_order', 'code'],
                'constraints': [models.UniqueConstraint(fields=('dict_type', 'code'), name='uniq_dict_type_code')],
            },
        ),
    ]
