# Generated by Django 5.1.14
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapproval',
            name='project_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='项目名称', default=''),
        ),
    ]
