# Generated by Django 5.1.14
from django.db import migrations


def add_project_name_if_not_exists(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'documents_projectapproval' 
            AND column_name = 'project_name'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE documents_projectapproval 
                ADD COLUMN project_name varchar(200) DEFAULT '' NOT NULL
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_project_name_if_not_exists),
    ]
