# Generated by Django 5.1.14
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    # project_name was already created in 0001_initial.
    # Keep 0002 as a no-op to preserve migration chain compatibility.
    operations = []
