# Generated by Django 5.1.14
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_add_project_name_to_projectapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmaster',
            name='province_code',
            field=models.CharField(max_length=20, verbose_name='所在省'),
        ),
    ]
