# Generated by Django 5.1.14 on 2026-03-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_province_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmaster',
            name='status',
            field=models.CharField(default='启用', max_length=10, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='projectapproval',
            name='project_code',
            field=models.CharField(max_length=12, verbose_name='项目编码'),
        ),
        migrations.AlterField(
            model_name='projectapproval',
            name='project_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='projectmaster',
            name='province_code',
            field=models.CharField(max_length=6, verbose_name='所在省'),
        ),
    ]
