# Generated by Django 6.0.3 on 2026-03-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_projectmasterlog_change_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmaster",
            name="org_code",
        ),
    ]
