# Generated by Django 6.0.3 on 2026-03-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_remove_projectmaster_org_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project_code", models.CharField(max_length=12, verbose_name="项目编码")),
                ("approval_type", models.CharField(choices=[("update", "修改"), ("delete", "删除")], max_length=10, verbose_name="审批类型")),
                ("before_data", models.JSONField(blank=True, null=True, verbose_name="修改前数据")),
                ("after_data", models.JSONField(blank=True, null=True, verbose_name="修改后数据")),
                ("change_note", models.CharField(blank=True, max_length=200, verbose_name="修改说明")),
                ("submitter", models.CharField(max_length=50, verbose_name="提交人")),
                ("approver", models.CharField(default="倪明珠", max_length=50, verbose_name="审批人")),
                ("status", models.CharField(choices=[("pending", "待审批"), ("approved", "已通过"), ("rejected", "已拒绝")], default="pending", max_length=10, verbose_name="审批状态")),
                ("submit_time", models.DateTimeField(auto_now_add=True, verbose_name="提交时间")),
                ("approve_time", models.DateTimeField(blank=True, null=True, verbose_name="审批时间")),
                ("approve_note", models.CharField(blank=True, max_length=200, verbose_name="审批意见")),
            ],
            options={
                "verbose_name": "项目审批",
                "verbose_name_plural": "项目审批",
                "ordering": ["-submit_time"],
            },
        ),
    ]
