# Generated by Django 6.0.3 on 2026-03-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_tag_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('note', '学习笔记'), ('essay', '日常随笔')], max_length=10, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectapproval',
            name='approval_type',
            field=models.CharField(choices=[('update', '修改'), ('delete', '删除'), ('import', '导入'), ('export', '导出')], max_length=10, verbose_name='审批类型'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
