# Generated by Django 6.0.3 on 2026-03-26 17:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_article_article_type_alter_article_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('party_name', models.CharField(max_length=200, verbose_name='单位名称')),
                ('party_type', models.CharField(choices=[('OWNER', '业主'), ('SUPPLIER', '供应商'), ('SUBCONTRACTOR', '分包商'), ('OTHER_VENDOR', '其他外委单位')], max_length=20, verbose_name='单位类型')),
                ('credit_code', models.CharField(max_length=18, unique=True, verbose_name='统一社会信用代码')),
                ('contact_name', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='联系电话')),
                ('status', models.CharField(default='ACTIVE', max_length=20, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '往来单位',
                'verbose_name_plural': '往来单位',
                'ordering': ['party_name'],
                'indexes': [models.Index(fields=['party_name'], name='idx_counterparty_name')],
            },
        ),
        migrations.CreateModel(
            name='ContractMaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_code_snapshot', models.CharField(max_length=12, verbose_name='项目主数据编码快照')),
                ('contract_ct_code', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^CT\\d{12}$', 'CT码格式必须为CT+12位数字')], verbose_name='合同CT码')),
                ('contract_name', models.CharField(max_length=200, verbose_name='合同名称')),
                ('contract_no', models.CharField(blank=True, max_length=100, verbose_name='合同编号')),
                ('source_system', models.CharField(choices=[('SUBCONTRACT', '分包系统'), ('SUPPLYCHAIN', '供应链系统'), ('ZHZZ', '智慧中咨系统'), ('PROJECT', '项管系统'), ('MANUAL', '手工录入')], max_length=20, verbose_name='来源系统')),
                ('source_record_id', models.CharField(blank=True, max_length=100, verbose_name='来源记录ID')),
                ('source_contract_no', models.CharField(blank=True, max_length=100, verbose_name='来源合同编号')),
                ('contract_direction', models.CharField(choices=[('INCOME', '收入合同'), ('EXPENSE', '支出合同'), ('NONE', '无收出合同')], max_length=20, verbose_name='合同方向')),
                ('contract_category', models.CharField(choices=[('MAIN', '主合同'), ('SUBCONTRACT', '分包合同'), ('PURCHASE', '采购合同'), ('SERVICE', '服务合同'), ('OTHER', '其他')], max_length=20, verbose_name='合同分类')),
                ('undertaking_dept_code', models.CharField(blank=True, max_length=50, verbose_name='承担部门编码')),
                ('undertaking_dept_name', models.CharField(blank=True, max_length=100, verbose_name='承担部门名称')),
                ('contract_year', models.CharField(blank=True, max_length=4, verbose_name='合同年份')),
                ('counterparty_name_snapshot', models.CharField(max_length=200, verbose_name='签约方名称快照')),
                ('sign_date', models.DateField(blank=True, null=True, verbose_name='签订日期')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='完结日期')),
                ('original_amount_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='原始含税金额')),
                ('original_amount_notax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='原始不含税金额')),
                ('original_tax_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='原始税率')),
                ('current_amount_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='当前含税金额')),
                ('current_amount_notax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='当前不含税金额')),
                ('current_tax_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='当前税率')),
                ('approved_adjustment_count', models.PositiveIntegerField(default=0, verbose_name='已通过调整次数')),
                ('last_adjustment_date', models.DateField(blank=True, null=True, verbose_name='最近一次已通过调整日期')),
                ('contract_status', models.CharField(choices=[('DRAFT', '草稿'), ('SIGNED', '已签订'), ('ACTIVE', '履约中'), ('CLOSED', '已完结'), ('TERMINATED', '已终止')], default='SIGNED', max_length=20, verbose_name='合同状态')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('data_version', models.PositiveIntegerField(default=1, verbose_name='数据版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='documents.projectmaster', verbose_name='所属项目')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='documents.counterparty', verbose_name='签约相对方')),
            ],
            options={
                'verbose_name': '合同主表',
                'verbose_name_plural': '合同主表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractAdjustment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_code_snapshot', models.CharField(max_length=12, verbose_name='项目主数据编码快照')),
                ('contract_ct_code_snapshot', models.CharField(max_length=14, verbose_name='合同CT码快照')),
                ('contract_name_snapshot', models.CharField(max_length=200, verbose_name='合同名称快照')),
                ('adjustment_type', models.CharField(choices=[('SUPPLEMENT', '补充合同/补充协议'), ('FINAL_SETTLEMENT', '最终结算'), ('MANUAL_CORRECTION', '手工修正'), ('OTHER', '其他')], max_length=20, verbose_name='调整类型')),
                ('adjustment_no', models.CharField(max_length=100, verbose_name='调整单号')),
                ('adjustment_date', models.DateField(verbose_name='调整日期')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('before_amount_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='调整前含税金额')),
                ('before_amount_notax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='调整前不含税金额')),
                ('before_tax_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='调整前税率')),
                ('before_counterparty_name', models.CharField(blank=True, max_length=200, verbose_name='调整前签约方名称')),
                ('change_amount_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='本次含税调整金额')),
                ('change_amount_notax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='本次不含税调整金额')),
                ('after_tax_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='调整后税率')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('after_amount_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='调整后含税金额')),
                ('after_amount_notax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='调整后不含税金额')),
                ('after_counterparty_name', models.CharField(blank=True, max_length=200, verbose_name='调整后签约方名称')),
                ('approval_status', models.CharField(choices=[('DRAFT', '草稿'), ('IN_REVIEW', '审批中'), ('APPROVED', '审批通过'), ('RETURNED', '退回')], default='DRAFT', max_length=20, verbose_name='审批状态')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('approver_name', models.CharField(default='倪明珠', max_length=50, verbose_name='审批人姓名')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批通过时间')),
                ('approval_comment', models.CharField(blank=True, max_length=500, verbose_name='审批意见')),
                ('return_reason', models.CharField(blank=True, max_length=500, verbose_name='退回原因')),
                ('approval_suggestion', models.TextField(blank=True, verbose_name='审批辅助建议')),
                ('suggestion_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='建议生成时间')),
                ('source_system', models.CharField(choices=[('SUBCONTRACT', '分包系统'), ('SUPPLYCHAIN', '供应链系统'), ('ZHZZ', '智慧中咨系统'), ('PROJECT', '项管系统'), ('MANUAL', '手工录入')], max_length=20, verbose_name='来源系统')),
                ('source_record_id', models.CharField(blank=True, max_length=100, verbose_name='来源记录ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contract_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_adjustments', to='documents.projectmaster', verbose_name='项目')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_contract_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='documents.contractmaster', verbose_name='合同')),
                ('after_counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_adjustments', to='documents.counterparty', verbose_name='调整后签约方')),
                ('before_counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='before_adjustments', to='documents.counterparty', verbose_name='调整前签约方')),
            ],
            options={
                'verbose_name': '合同调整记录',
                'verbose_name_plural': '合同调整记录',
                'ordering': ['-adjustment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractAdjustmentActionLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('SUBMIT', '提交'), ('APPROVE', '通过'), ('RETURN', '退回'), ('EDIT', '修改')], max_length=20, verbose_name='动作类型')),
                ('action_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='动作说明')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='动作前状态')),
                ('to_status', models.CharField(blank=True, max_length=20, verbose_name='动作后状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_adjustment_actions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='documents.contractadjustment', verbose_name='调整记录')),
            ],
            options={
                'verbose_name': '合同调整动作日志',
                'verbose_name_plural': '合同调整动作日志',
                'ordering': ['-action_at', '-id'],
                'indexes': [models.Index(fields=['adjustment'], name='idx_adjlog_adjustment'), models.Index(fields=['action_type'], name='idx_adjlog_action'), models.Index(fields=['action_by'], name='idx_adjlog_user'), models.Index(fields=['action_at'], name='idx_adjlog_at'), models.Index(fields=['adjustment', 'action_at'], name='idx_adjlog_adjustment_at')],
            },
        ),
        migrations.AddIndex(
            model_name='contractmaster',
            index=models.Index(fields=['project'], name='idx_contract_project'),
        ),
        migrations.AddIndex(
            model_name='contractmaster',
            index=models.Index(fields=['counterparty'], name='idx_contract_counterparty'),
        ),
        migrations.AddIndex(
            model_name='contractmaster',
            index=models.Index(fields=['source_system'], name='idx_contract_source'),
        ),
        migrations.AddIndex(
            model_name='contractmaster',
            index=models.Index(fields=['contract_direction'], name='idx_contract_direction'),
        ),
        migrations.AddIndex(
            model_name='contractmaster',
            index=models.Index(fields=['contract_category'], name='idx_contract_category'),
        ),
        migrations.AddIndex(
            model_name='contractmaster',
            index=models.Index(fields=['contract_status'], name='idx_contract_status'),
        ),
        migrations.AddIndex(
            model_name='contractmaster',
            index=models.Index(fields=['undertaking_dept_code'], name='idx_contract_dept'),
        ),
        migrations.AddIndex(
            model_name='contractmaster',
            index=models.Index(fields=['contract_year'], name='idx_contract_year'),
        ),
        migrations.AddIndex(
            model_name='contractmaster',
            index=models.Index(fields=['project_code_snapshot'], name='idx_contract_proj_snapshot'),
        ),
        migrations.AddIndex(
            model_name='contractmaster',
            index=models.Index(fields=['project', 'contract_direction'], name='idx_contract_proj_dir'),
        ),
        migrations.AddIndex(
            model_name='contractmaster',
            index=models.Index(fields=['project', 'contract_category'], name='idx_contract_proj_cat'),
        ),
        migrations.AddIndex(
            model_name='contractmaster',
            index=models.Index(fields=['undertaking_dept_code', 'contract_year'], name='idx_contract_dept_year'),
        ),
        migrations.AddIndex(
            model_name='contractmaster',
            index=models.Index(fields=['project', 'contract_year'], name='idx_contract_proj_year'),
        ),
        migrations.AddIndex(
            model_name='contractmaster',
            index=models.Index(fields=['source_system', 'source_contract_no'], name='idx_contract_source_no'),
        ),
        migrations.AddIndex(
            model_name='contractadjustment',
            index=models.Index(fields=['contract'], name='idx_adj_contract'),
        ),
        migrations.AddIndex(
            model_name='contractadjustment',
            index=models.Index(fields=['project'], name='idx_adj_project'),
        ),
        migrations.AddIndex(
            model_name='contractadjustment',
            index=models.Index(fields=['approval_status'], name='idx_adj_status'),
        ),
        migrations.AddIndex(
            model_name='contractadjustment',
            index=models.Index(fields=['adjustment_type'], name='idx_adj_type'),
        ),
        migrations.AddIndex(
            model_name='contractadjustment',
            index=models.Index(fields=['adjustment_date'], name='idx_adj_date'),
        ),
        migrations.AddIndex(
            model_name='contractadjustment',
            index=models.Index(fields=['source_system'], name='idx_adj_source'),
        ),
        migrations.AddIndex(
            model_name='contractadjustment',
            index=models.Index(fields=['contract_ct_code_snapshot'], name='idx_adj_ct_snapshot'),
        ),
        migrations.AddIndex(
            model_name='contractadjustment',
            index=models.Index(fields=['contract', 'approval_status'], name='idx_adj_contract_status'),
        ),
        migrations.AddIndex(
            model_name='contractadjustment',
            index=models.Index(fields=['contract', 'adjustment_type'], name='idx_adj_contract_type'),
        ),
        migrations.AddIndex(
            model_name='contractadjustment',
            index=models.Index(fields=['project', 'approval_status'], name='idx_adj_project_status'),
        ),
        migrations.AddIndex(
            model_name='contractadjustment',
            index=models.Index(fields=['contract_ct_code_snapshot', 'approval_status'], name='idx_adj_ct_status'),
        ),
    ]
