# Generated by Django 5.1.14 on 2026-03-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_counterparty_contractmaster_contractadjustment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractadjustment',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='contractadjustment',
            name='updated_by',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='contractmaster',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='contractmaster',
            name='updated_by',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='updated_by',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='更新人'),
        ),
    ]
