# Generated by Django 5.1.14 on 2026-03-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_counterparty_phone_back_to_255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmaster',
            name='execution_project_code_snapshot',
            field=models.CharField(blank=True, max_length=12, verbose_name='执行层项目编码快照'),
        ),
        migrations.AlterField(
            model_name='contractmaster',
            name='execution_project_name_snapshot',
            field=models.CharField(blank=True, max_length=100, verbose_name='执行层项目名称快照'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='party_type',
            field=models.CharField(choices=[('OWNER', '业主'), ('SUPPLIER', '供应商'), ('SUBCONTRACTOR', '分包商'), ('SUPPLY_SUB', '供应&分包商'), ('OTHER_VENDOR', '其他外委单位')], max_length=20, verbose_name='单位类型'),
        ),
        migrations.AlterField(
            model_name='projectapproval',
            name='change_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='修改说明'),
        ),
        migrations.AlterField(
            model_name='projectmasterlog',
            name='change_note',
            field=models.TextField(blank=True, verbose_name='修改说明'),
        ),
    ]
