# Generated by Django 5.1.14 on 2026-03-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_contractmaster_schema_refactor'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contractmaster',
            name='idx_contract_source_no',
        ),
        migrations.AlterField(
            model_name='projectmaster',
            name='project_name',
            field=models.CharField(max_length=100, verbose_name='项目名称'),
        ),
    ]
